# Generated by Django 5.2 on 2025-11-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_created_2e2442_idx",
            old_name="main_post_created_16b2dc_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_status_ecf387_idx",
            old_name="main_post_status_af64c5_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_categor_4138d2_idx",
            old_name="main_post_categor_3f0b4d_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_author__f2f966_idx",
            old_name="main_post_author__698eef_idx",
        ),
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
