FROM python:3.13.6-slim-trixie

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    zsh \
    nodejs \
    openssh-client \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /sheep_drf

COPY ../requirements/ ./requirements/
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r ./requirements/dev.txt

RUN mkdir -p /root/.ssh
COPY .ssh/ /root/.ssh/
RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/*

COPY .. .

ENV PYTHONPATH="/sheep_drf"
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir /usr/local/bin

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
RUN echo 'eval "$(starship init zsh)"' >> /root/.zshrc

RUN mkdir -p /root/.config && \
    echo '[character]' >> /root/.config/starship.toml && \
    echo 'success_symbol = "[➜](bold green)"' >> /root/.config/starship.toml && \
    echo 'error_symbol = "[✖︎](bold red)"' >> /root/.config/starship.toml && \
    echo '[nodejs]' >> /root/.config/starship.toml && \
    echo 'disabled = true' >> /root/.config/starship.toml && \
    echo '[python]' >> /root/.config/starship.toml && \
    echo 'disabled = true' >> /root/.config/starship.toml

RUN git config --global user.name "slivapyt" && \
    git config --global user.email "faer2325@gmail.com"

